name: Validate Code Format

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  validate_code_format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Build Environment
        uses: ./.github/workflows/setup_build_environment
        with:
          python_version: '3.9'
      
      - name: Check Format
        run: make format CHECK=true
