name: prcheck

on: [pull_request]

jobs:
  lint:
    name: runner / lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -e '.[dev]'
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff for linting and formatting
        run: ruff check .

  test:
    name: runner / pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -e '.[dev]'
      - name: Run tests
        run: pytest